import type { TScenarioId } from "@/constants/projects";
import type { Scenario } from "./types";

/**
 * Scenario definitions. Coordinates are on a 1000 × 560 canvas and read
 * left to right, the way Make lays a flow out. Names and actions are kept
 * in English on purpose — they are module labels, not prose.
 */

const hero: Scenario = {
  id: "hero",
  name: "deal-stage → docs · enrichment · mirror",
  schedule: "Immediately (webhook)",
  nodes: [
    {
      id: "t",
      app: "brevo",
      kind: "trigger",
      label: "Brevo",
      action: "Watch deals",
      x: 96,
      y: 280,
      note: "Fires the moment a deal changes stage in the Brevo CRM.",
    },
    {
      id: "r",
      app: "router",
      kind: "router",
      label: "Router",
      action: "3 routes",
      x: 292,
      y: 280,
      note: "Each route carries its own filter. Bundles that match none are dropped, and logged.",
    },
    {
      id: "pd",
      app: "pandadoc",
      kind: "action",
      label: "PandaDoc",
      action: "Create document",
      x: 500,
      y: 108,
      note: "Builds the order form from the deal's template and pre-fills it from CRM fields.",
    },
    {
      id: "sl",
      app: "slack",
      kind: "action",
      label: "Slack",
      action: "Post to #sales-won",
      x: 716,
      y: 108,
      note: "One message per won deal, with owner, amount and the document link.",
    },
    {
      id: "en",
      app: "python",
      kind: "ai",
      label: "Enrich API",
      action: "Waterfall enrich",
      x: 500,
      y: 280,
      note: "Internal Python service: email → phone → company → tech stack, one provider at a time until one answers.",
    },
    {
      id: "bu",
      app: "brevo",
      kind: "action",
      label: "Brevo",
      action: "Update contact",
      x: 716,
      y: 280,
      note: "Writes the enriched fields back so the sales rep sees them before the first call.",
    },
    {
      id: "ph",
      app: "planhat",
      kind: "action",
      label: "Planhat",
      action: "Upsert customer",
      x: 920,
      y: 280,
      note: "Customer-success gets the same record, without a second form.",
    },
    {
      id: "sb",
      app: "supabase",
      kind: "store",
      label: "Supabase",
      action: "Upsert mirror row",
      x: 500,
      y: 452,
      note: "Keeps the Postgres mirror in step so internal tools can filter on fields the Brevo API cannot.",
    },
    {
      id: "er",
      app: "slack",
      kind: "action",
      label: "Slack",
      action: "Alert #ops-errors",
      x: 716,
      y: 430,
      note: "Error handler. A failed bundle becomes a message with the payload attached — never a silent gap.",
    },
  ],
  edges: [
    { id: "e1", from: "t", to: "r" },
    { id: "e2", from: "r", to: "pd", filter: "stage = won" },
    { id: "e3", from: "pd", to: "sl" },
    { id: "e4", from: "r", to: "en", filter: "new lead" },
    { id: "e5", from: "en", to: "bu" },
    { id: "e6", from: "bu", to: "ph" },
    { id: "e7", from: "r", to: "sb", filter: "always" },
    { id: "e8", from: "en", to: "er", error: true },
  ],
};

const sync: Scenario = {
  id: "sync",
  name: "brevo → revenue stack",
  schedule: "Immediately (webhook)",
  nodes: [
    {
      id: "t",
      app: "brevo",
      kind: "trigger",
      label: "Brevo",
      action: "Watch contacts",
      x: 110,
      y: 280,
    },
    {
      id: "r",
      app: "router",
      kind: "router",
      label: "Router",
      action: "5 routes",
      x: 340,
      y: 280,
    },
    {
      id: "a",
      app: "pandadoc",
      kind: "action",
      label: "PandaDoc",
      action: "Create doc",
      x: 620,
      y: 80,
    },
    {
      id: "b",
      app: "planhat",
      kind: "action",
      label: "Planhat",
      action: "Upsert",
      x: 620,
      y: 180,
    },
    {
      id: "c",
      app: "qobra",
      kind: "action",
      label: "Qobra",
      action: "Sync deal",
      x: 620,
      y: 280,
    },
    {
      id: "d",
      app: "gong",
      kind: "action",
      label: "Gong",
      action: "Tag account",
      x: 620,
      y: 380,
    },
    {
      id: "e",
      app: "chilipiper",
      kind: "action",
      label: "Chili Piper",
      action: "Book handoff",
      x: 620,
      y: 480,
    },
    {
      id: "s",
      app: "slack",
      kind: "action",
      label: "Slack",
      action: "Notify",
      x: 880,
      y: 280,
    },
  ],
  edges: [
    { id: "e1", from: "t", to: "r" },
    { id: "e2", from: "r", to: "a", filter: "won" },
    { id: "e3", from: "r", to: "b", filter: "customer" },
    { id: "e4", from: "r", to: "c", filter: "deal" },
    { id: "e5", from: "r", to: "d", filter: "call" },
    { id: "e6", from: "r", to: "e", filter: "meeting" },
    { id: "e7", from: "c", to: "s" },
  ],
};

const enrich: Scenario = {
  id: "enrich",
  name: "contact → enrichment waterfall",
  schedule: "Immediately (webhook)",
  nodes: [
    {
      id: "w",
      app: "webhook",
      kind: "trigger",
      label: "Webhook",
      action: "Contact created",
      x: 100,
      y: 280,
    },
    {
      id: "api",
      app: "python",
      kind: "ai",
      label: "Enrich API",
      action: "Normalize",
      x: 320,
      y: 280,
    },
    {
      id: "r",
      app: "router",
      kind: "router",
      label: "Router",
      action: "3 routes",
      x: 520,
      y: 280,
    },
    {
      id: "lc",
      app: "langchain",
      kind: "ai",
      label: "LangChain",
      action: "Company summary",
      x: 740,
      y: 140,
    },
    {
      id: "ph",
      app: "python",
      kind: "ai",
      label: "Phone API",
      action: "Waterfall",
      x: 740,
      y: 280,
    },
    {
      id: "ts",
      app: "python",
      kind: "ai",
      label: "Techstack API",
      action: "Detect stack",
      x: 740,
      y: 420,
    },
    {
      id: "b",
      app: "brevo",
      kind: "action",
      label: "Brevo",
      action: "Update contact",
      x: 930,
      y: 280,
    },
  ],
  edges: [
    { id: "e1", from: "w", to: "api" },
    { id: "e2", from: "api", to: "r" },
    { id: "e3", from: "r", to: "lc", filter: "has domain" },
    { id: "e4", from: "r", to: "ph", filter: "no phone" },
    { id: "e5", from: "r", to: "ts", filter: "b2b" },
    { id: "e6", from: "lc", to: "b" },
    { id: "e7", from: "ph", to: "b" },
    { id: "e8", from: "ts", to: "b" },
  ],
};

const mirror: Scenario = {
  id: "mirror",
  name: "crm → supabase mirror",
  schedule: "Webhook + every 15 min",
  nodes: [
    {
      id: "t",
      app: "brevo",
      kind: "trigger",
      label: "Brevo",
      action: "Watch changes",
      x: 110,
      y: 190,
    },
    {
      id: "m",
      app: "make",
      kind: "action",
      label: "Make",
      action: "Normalize",
      x: 360,
      y: 190,
    },
    {
      id: "c",
      app: "cron",
      kind: "trigger",
      label: "Schedule",
      action: "Every 15 min",
      x: 110,
      y: 390,
    },
    {
      id: "p",
      app: "python",
      kind: "ai",
      label: "Sync job",
      action: "Diff & backfill",
      x: 360,
      y: 390,
    },
    {
      id: "s",
      app: "supabase",
      kind: "store",
      label: "Supabase",
      action: "Upsert",
      x: 620,
      y: 290,
    },
    {
      id: "u",
      app: "platform",
      kind: "action",
      label: "Internal tools",
      action: "Query mirror",
      x: 880,
      y: 290,
    },
  ],
  edges: [
    { id: "e1", from: "t", to: "m" },
    { id: "e2", from: "m", to: "s" },
    { id: "e3", from: "c", to: "p" },
    { id: "e4", from: "p", to: "s" },
    { id: "e5", from: "s", to: "u" },
  ],
};

const agents: Scenario = {
  id: "agents",
  name: "slack question → dust agent → crm",
  schedule: "On message",
  nodes: [
    {
      id: "u",
      app: "user",
      kind: "trigger",
      label: "Sales rep",
      action: "Asks in Slack",
      x: 100,
      y: 280,
    },
    {
      id: "s",
      app: "slack",
      kind: "action",
      label: "Slack",
      action: "Thread",
      x: 330,
      y: 280,
    },
    {
      id: "d",
      app: "dust",
      kind: "ai",
      label: "Dust agent",
      action: "Reason · tool calls",
      x: 560,
      y: 280,
    },
    {
      id: "b",
      app: "brevo",
      kind: "action",
      label: "Brevo",
      action: "Read deals",
      x: 800,
      y: 150,
    },
    {
      id: "m",
      app: "supabase",
      kind: "store",
      label: "Supabase",
      action: "Query mirror",
      x: 800,
      y: 280,
    },
    {
      id: "g",
      app: "gong",
      kind: "action",
      label: "Gong",
      action: "Call notes",
      x: 800,
      y: 410,
    },
  ],
  edges: [
    { id: "e1", from: "u", to: "s" },
    { id: "e2", from: "s", to: "d" },
    { id: "e3", from: "d", to: "b", filter: "pipeline" },
    { id: "e4", from: "d", to: "m", filter: "history" },
    { id: "e5", from: "d", to: "g", filter: "calls" },
  ],
};

const platform: Scenario = {
  id: "platform",
  name: "apis → platform → consumers",
  schedule: "Always on",
  nodes: [
    {
      id: "a",
      app: "python",
      kind: "ai",
      label: "Enrich APIs",
      action: "Contact · phone · company",
      x: 110,
      y: 150,
    },
    {
      id: "l",
      app: "langchain",
      kind: "ai",
      label: "AI services",
      action: "LangChain",
      x: 110,
      y: 280,
    },
    {
      id: "s",
      app: "supabase",
      kind: "store",
      label: "Supabase",
      action: "Mirror & auth",
      x: 110,
      y: 410,
    },
    {
      id: "p",
      app: "platform",
      kind: "action",
      label: "Internal platform",
      action: "Docs · metering",
      x: 440,
      y: 280,
    },
    {
      id: "m",
      app: "make",
      kind: "action",
      label: "Make",
      action: "Scenarios",
      x: 760,
      y: 150,
    },
    {
      id: "d",
      app: "dust",
      kind: "ai",
      label: "Dust",
      action: "Agents",
      x: 760,
      y: 280,
    },
    {
      id: "u",
      app: "user",
      kind: "action",
      label: "Ops teams",
      action: "Self-serve",
      x: 760,
      y: 410,
    },
  ],
  edges: [
    { id: "e1", from: "a", to: "p" },
    { id: "e2", from: "l", to: "p" },
    { id: "e3", from: "s", to: "p" },
    { id: "e4", from: "p", to: "m" },
    { id: "e5", from: "p", to: "d" },
    { id: "e6", from: "p", to: "u" },
  ],
};

export const SCENARIOS: Record<TScenarioId, Scenario> = {
  hero,
  sync,
  enrich,
  mirror,
  agents,
  platform,
};
